spring.application.name=Spring-Cloud-Stream
server.port=8083
spring.cloud.stream.kafka.binder.brokers=localhost:9092
spring.cloud.stream.bindings.pageEventConsumer-in-0.destination=T1
spring.cloud.stream.bindings.pageEventSupplier-out-0.destination=T2
spring.cloud.stream.bindings.kStreamFunction-in-0.destination=T2
spring.cloud.stream.bindings.kStreamFunction-out-0.destination=T3
spring.cloud.stream.bindings.pageEventSupplier-out-0.producer.poller.fixed-delay=200
spring.cloud.stream.kafka.streams.binder.configuration.commit.interval.ms=1000
spring.cloud.function.definition=pageEventConsumer;pageEventSupplier;kStreamFunction
